### ISSUE TITLE
How to insert multiple addresses or mobile numbers?

### ISSUE THREAD

**Issue by sommella** [gsilano/EuropeCV#12]
Hi,
I would like to add multiple addresses and mobile numbers to my cv, having the graphical symbol for each, how can I do that?
Thanks

**Comment by gsilano** [comment]
Hi @skonvols2k , the easiest way to get more addresses and mobile phones is to separate them using a coma. In other words, if you see the tex example given in the `templates` directory, just add the following line

`\ecvaddress{(First addres), (Second address)}`

instead of

`\ecvaddress{(Remove if not relevant)}`

Similarly, you can add more mobile phones.

**Comment by sommella** [comment]
Hi,
just tested, this way the 2 addresses come on the same line and the logo isn't repeated.
Same with phones. Doesn't look like professionally formatted this way.

**Comment by gsilano** [comment]
Ok, @skonvols2k. I'm thinking about how to integrate this functionality while maintaining portability with the older version.
I will let you know when it is integrated into the package.

**Comment by gsilano** [comment]
I have just integrated the changes necessary to maintain portability with the previous version of the package trying to understand the problem you pointed out. I thought that more mobile numbers could be inserted using a coma, I suggested. Therefore, I decided not to implement this functionality. Instructions on how to use the package can be found in the manual and in the examples.
